

class Observation:
    """
    Observations are generated by actions that observe different aspects of the game state.
    A few examples:
    - Perception check for vision
        Vision is granted based on Per vs stealth checks, or other such rolls. Reveals location/posture in the world.
    - Perception check for in depth view of a particular entity
        Yields information on the model information of the target of the observation.

    """
    def __init__(self):
        pass
